version: 2
updates:
- package-ecosystem: nuget
  directory: "/Source"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: System.Text.Json
      versions:
        - ">= 6.a"
        - "< 8"
    - dependency-name: System.Net.Http.Json
      versions:
        - ">= 6.a"
        - "< 8"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
