language: csharp
matrix:
  include:
    - os: linux
      dist: trusty
      mono: latest
      dotnet: 2.1.3
      sudo: required
      env: MONO_BASE_PATH=/usr/lib/mono/
services:
  - docker
before_install:
  - |
    sudo sed -i 's@^DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock"$@DOCKER_OPTS="-H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock"@' /etc/default/docker
    sudo service docker restart
    DOTNET_INSTALL_DIR="$PWD/.dotnetsdk"
    curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version "1.1.6" --install-dir "$DOTNET_INSTALL_DIR" --no-path
    curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version "2.1.3" --install-dir "$DOTNET_INSTALL_DIR" --no-path
    export PATH="$DOTNET_INSTALL_DIR:$PATH"
script:
  - |
    mostRecentTag=$(git describe --abbrev=0 --tags --always)
    if [[ $mostRecentTag != v* ]]; then
        mostRecentTag='v1.0.0'
    fi
    mostRecentVersion=$(echo "$mostRecentTag" | cut -c 2-)
    FrameworkPathOverride=$MONO_BASE_PATH/4.5.2-api/ $(pwd)/Tools/build/build.sh '--target=Test' "--softwareVersion=$mostRecentVersion" "--buildNumber=$TRAVIS_BUILD_NUMBER"
notifications:
  email: false