language: csharp
matrix:
  include:
    - os: linux
      dist: bionic
      mono: none
      dotnet: 3.0
      sudo: required
services:
  - docker
before_install:
  - sudo cat /etc/default/docker
  - sudo cat /lib/systemd/system/docker.service
  - sudo sed -i 's@^ExecStart=/usr/bin/dockerd -H fd://$@ExecStart=/usr/bin/dockerd -H tcp://127.0.0.1:2375@' /lib/systemd/system/docker.service
  - sudo cat /lib/systemd/system/docker.service
  - sudo systemctl daemon-reload
  - sudo systemctl restart docker.service
  - sudo netstat -lntp | grep dockerd
script:
  - |
    mostRecentTag=$(git describe --abbrev=0 --tags --always)
    echo "Detected most recent tag is '$mostRecentTag'"
    if [[ $mostRecentTag != v* ]]; then
        mostRecentTag='v1.0.0'
        if [[ "${TRAVIS_TAG}" != "" ]]; then exit 1; fi
    fi
    mostRecentVersion=$(echo "$mostRecentTag" | cut -c 2-)
    $(pwd)/Tools/build/build.sh '--target=Test' "--softwareVersion=$mostRecentVersion" "--buildNumber=$TRAVIS_BUILD_NUMBER"
notifications:
  email: false
