FROM microsoft/windowsservercore:10.0.14393.1770

ENV ERLANG_HOME="c:\erlang" \
    ERLANG_VERSION="20.1" \
    RABBITMQ_VERSION="3.6.14" \
    RABBITMQ_BASE="c:\rabbitmq" \
    RABBITMQ_CONFIG_FILE="c:\rabbitmq\rmqsettings"

SHELL ["powershell", "-Command"]

EXPOSE 1883 4369 5671 5672 8883 15671 15672 15674 15675 25672 61613 61614

RUN $erlangInstaller = Join-Path -Path $env:Temp -ChildPath 'otp_win64.exe'; \
    Invoke-WebRequest -UseBasicParsing -Uri "http://erlang.org/download/otp_win64_$env:ERLANG_VERSION.exe" -OutFile $erlangInstaller; \
    Unblock-File -Path $erlangInstaller; \
    Start-Process -NoNewWindow -Wait -FilePath $erlangInstaller -ArgumentList /S, /D=$env:ERLANG_HOME; \
    Remove-Item -Force -Path $erlangInstaller; \
    $rabbitZip = Join-Path -Path $env:Temp -ChildPath 'rabbitmq.zip'; \
    Invoke-WebRequest -UseBasicParsing -Uri "https://www.rabbitmq.com/releases/rabbitmq-server/v$env:RABBITMQ_VERSION/rabbitmq-server-windows-$env:RABBITMQ_VERSION.zip" -OutFile $rabbitZip; \
    Unblock-File -Path $rabbitZip; \
    Expand-Archive -Path $rabbitZip -DestinationPath 'c:\'; \
    Remove-Item -Force -Path $rabbitZip; \
    Rename-Item -Path "c:\rabbitmq_server-$env:RABBITMQ_VERSION" -NewName 'c:\rabbitmq'; \
    Remove-Item -Force -Path C:\rabbitmq\*.txt; \
    $utf8NoBomEncoding = New-Object System.Text.UTF8Encoding $False; \
    [System.IO.File]::WriteAllText('C:\rabbitmq\rmqsettings.config', '[{rabbit,[{loopback_users, []}]}].', $utf8NoBomEncoding); \
    C:\rabbitmq\sbin\rabbitmq-plugins.bat enable --offline rabbitmq_management rabbitmq_federation rabbitmq_federation_management rabbitmq_management_visualiser rabbitmq_mqtt rabbitmq_stomp

CMD c:\rabbitmq\sbin\rabbitmq-server.bat